name: release

on:
  push:
    tags:
      - "v*"

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.4
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "src-tauri -> target"
          cache-all-crates: true
      - run: pnpm install --frozen-lockfile
      - run: pnpm tauri build
