// Copyright (c) Microsoft Corporation and Contributors. All rights reserved.
// Licensed under the MIT License.

import { test } from 'node:test';
import * as assert from 'node:assert/strict';
import * as fs from 'fs';
import * as path from 'path';

// docs/npm-usage.md is generated by scripts/generate-docs.mjs from the TypeScript API surface. A
// multi-paragraph JSDoc comment (CommonOptions.signal) used to be emitted verbatim, so its embedded
// newlines terminated the table row and dumped the rest as body text — in every command table.
// npm scripts run from src/winapp-npm, matching how ui-record-guard.test.ts resolves generated files.
const DOC_PATH = path.resolve(process.cwd(), '..', '..', 'docs', 'npm-usage.md');

function readDoc(): string[] {
  return fs.readFileSync(DOC_PATH, 'utf8').split(/\r?\n/);
}

test('every generated Markdown table row is a single well-formed line', () => {
  const lines = readDoc();
  const broken: string[] = [];
  let inFence = false;

  for (const line of lines) {
    if (line.startsWith('```')) {
      inFence = !inFence;
      continue;
    }
    if (inFence || !line.startsWith('|')) continue;
    if (!line.trimEnd().endsWith('|')) broken.push(line);
  }

  assert.deepEqual(broken, [], 'table rows must open and close with a pipe on one line');
});

test('CommonOptions properties are not repeated in per-command option tables', () => {
  const lines = readDoc();
  const start = lines.indexOf('## CLI command wrappers');
  const end = lines.indexOf('## Utility functions');
  assert.ok(start >= 0 && end > start, 'expected a CLI command wrappers section');

  // The trailing "Types reference" section deliberately expands every exported interface, inherited
  // members included; only the per-command tables must stay free of CommonOptions noise.
  const wrapperSection = lines.slice(start, end);
  const leaked = wrapperSection.filter((line) =>
    ['quiet', 'verbose', 'cwd', 'signal'].some((prop) => line.startsWith(`| \`${prop}\``))
  );

  assert.deepEqual(leaked, [], 'CommonOptions belong in the shared note, not in each command table');
});

test('the single CommonOptions signal row carries the full cancellation contract', () => {
  const lines = readDoc();
  const start = lines.indexOf('### `CommonOptions`');
  const end = lines.indexOf('### `WinappResult`');
  assert.ok(start >= 0 && end > start, 'expected a CommonOptions section');

  const signalRows = lines.slice(start, end).filter((line) => line.startsWith('| `signal`'));
  assert.equal(signalRows.length, 1);
  assert.ok(
    signalRows[0].includes('AbortError'),
    'the flattened signal row must keep its whole multi-paragraph contract'
  );
});

test('the shared-options note lists every CommonOptions property', () => {
  const doc = fs.readFileSync(DOC_PATH, 'utf8');
  const notes = doc.match(/\[CommonOptions\]\(#commonoptions\) \(([^)]*)\)/g) ?? [];

  assert.ok(notes.length > 0, 'expected at least one shared-options note');
  for (const note of notes) {
    for (const prop of ['quiet', 'verbose', 'cwd', 'signal']) {
      assert.ok(note.includes(`\`${prop}\``), `${note} must mention ${prop}`);
    }
  }
});
