// Copyright (c) Microsoft Corporation and Contributors. All rights reserved.
// Licensed under the MIT License.

import { test, mock, afterEach } from 'node:test';
import * as assert from 'node:assert/strict';
import { EventEmitter } from 'node:events';
// Use import-equals so childProcess is the REAL cached module object (not an
// __importStar copy). winapp-cli-utils calls `require('child_process').spawn`, so
// the mock must be installed on the same shared exports object to be observed.
import childProcess = require('child_process');

import { run, uiInvoke } from '../src/winapp-commands';

// The programmatic wrappers in src/winapp-commands.ts are AUTO-GENERATED by
// scripts/generate-commands.mjs. These tests capture the argv the generated
// `run` wrapper actually spawns, so a generator change cannot silently break the
// shipped TypeScript API — in particular the repeatable `--property` emission and
// the position of global flags relative to the `--` passthrough separator.

/**
 * Replace child_process.spawn with a fake that records the argv it is handed and
 * immediately resolves with a success exit code. winapp-cli-utils reads spawn off
 * the shared builtin module at call time, so mutating it here is observed by run().
 */
function captureSpawnArgs(): { calls: string[][] } {
  const state = { calls: [] as string[][] };
  mock.method(childProcess, 'spawn', ((_cmd: string, args: string[]) => {
    state.calls.push(args);
    const child = new EventEmitter() as EventEmitter & {
      stdout: EventEmitter;
      stderr: EventEmitter;
    };
    child.stdout = new EventEmitter();
    child.stderr = new EventEmitter();
    // Emit close after listeners are attached (spawn returns synchronously first).
    process.nextTick(() => child.emit('close', 0));
    return child;
  }) as unknown as typeof childProcess.spawn);
  return state;
}

afterEach(() => {
  mock.restoreAll();
});

test('uiInvoke forwards an explicitly empty action for native validation instead of automatic fallback', async () => {
  const state = captureSpawnArgs();
  await uiInvoke({ selector: 'AgreeCheckbox', app: 'myapp', action: '' });
  const argv = state.calls[0];
  const actionIndex = argv.indexOf('--action');
  assert.notEqual(actionIndex, -1);
  assert.equal(argv[actionIndex + 1], '');
});

test('uiInvoke omits only an undefined action and forwards every explicit action', async () => {
  const state = captureSpawnArgs();
  await uiInvoke({ selector: 'AgreeCheckbox', app: 'myapp' });
  assert.equal(state.calls[0].indexOf('--action'), -1);
  for (const action of ['invoke', 'select', 'toggle', 'toggle-on', 'toggle-off', 'expand', 'collapse']) {
    await uiInvoke({ selector: 'AgreeCheckbox', app: 'myapp', action });
    const argv = state.calls.at(-1)!;
    assert.equal(argv[argv.indexOf('--action') + 1], action);
  }
});

test('uiInvoke keeps execution target and action before the protected selector', async () => {
  const state = captureSpawnArgs();
  await uiInvoke({ selector: '--action', window: 1234, action: 'select', on: 'sandbox', quiet: true });
  const argv = state.calls[0];
  const separator = argv.indexOf('--');
  assert.deepEqual(argv.slice(separator + 1), ['--action']);
  for (const [flag, value] of [['--on', 'sandbox'], ['--action', 'select'], ['--window', '1234']]) {
    const index = argv.indexOf(flag);
    assert.ok(index > 1 && index < separator);
    assert.equal(argv[index + 1], value);
  }
  assert.ok(argv.indexOf('--quiet') < separator);
});

test('run emits repeatable --property as separate flag/value pairs and keeps --quiet before the -- passthrough', async () => {
  const state = captureSpawnArgs();

  await run({ property: ['A=1', 'B=2'], appArgs: ['--flag'], quiet: true });

  assert.equal(state.calls.length, 1, 'winapp CLI should be spawned exactly once');
  const argv = state.calls[0];

  // Each --property value must be emitted as its own flag/value pair.
  const propValues: string[] = [];
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--property') propValues.push(argv[i + 1]);
  }
  assert.deepEqual(
    propValues,
    ['A=1', 'B=2'],
    'each property must be a separate --property flag/value pair'
  );

  // Global flags (e.g. --quiet) must come before the `--` passthrough separator so
  // winapp consumes them instead of forwarding them to the launched app.
  const sep = argv.indexOf('--');
  const quiet = argv.indexOf('--quiet');
  assert.ok(quiet !== -1, '--quiet should be present');
  assert.ok(sep !== -1, 'the -- passthrough separator should be present');
  assert.ok(quiet < sep, '--quiet must come before the -- passthrough separator');

  // App args are forwarded verbatim after the separator.
  assert.deepEqual(argv.slice(sep + 1), ['--flag'], 'app args are forwarded after --');
});

test('run accepts a single scalar --property value', async () => {
  const state = captureSpawnArgs();

  await run({ property: 'X=9' });

  const argv = state.calls[0];
  const propValues: string[] = [];
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--property') propValues.push(argv[i + 1]);
  }
  assert.deepEqual(propValues, ['X=9'], 'a scalar property is emitted as one --property pair');
  assert.equal(argv.indexOf('--'), -1, 'no passthrough separator without appArgs');
});

test('run forwards the canonical `input` property as the first positional', async () => {
  const state = captureSpawnArgs();

  await run({ input: './dist' });

  const argv = state.calls[0];
  assert.equal(argv[0], 'run', 'first token is the run subcommand');
  assert.equal(argv[1], './dist', 'input is forwarded as the first positional');
});

test('run still honors the deprecated `inputFolder` alias (backward compatibility)', async () => {
  // The positional argument was renamed input-folder -> input; pre-rename callers
  // that pass `inputFolder` must keep working instead of silently running the cwd.
  const state = captureSpawnArgs();

  await run({ inputFolder: './dist' });

  const argv = state.calls[0];
  assert.equal(argv[1], './dist', 'the deprecated inputFolder alias is forwarded as the positional');
});

test('run prefers `input` over the deprecated `inputFolder` when both are set', async () => {
  const state = captureSpawnArgs();

  await run({ input: './new', inputFolder: './old' });

  const argv = state.calls[0];
  assert.equal(argv[1], './new', 'the canonical input wins over the deprecated alias');
  assert.equal(argv.indexOf('./old'), -1, 'the deprecated alias value is not forwarded when input is set');
});
