// Copyright (c) Microsoft Corporation and Contributors. All rights reserved.
// Licensed under the MIT License.

import { test, mock, afterEach } from 'node:test';
import * as assert from 'node:assert/strict';
import { EventEmitter } from 'node:events';
// Use import-equals so childProcess is the REAL cached module object (not an
// __importStar copy). winapp-cli-utils calls `require('child_process').spawn`, so
// the mock must be installed on the same shared exports object to be observed.
import childProcess = require('child_process');

import { run } from '../src/winapp-commands';

// The programmatic wrappers in src/winapp-commands.ts are AUTO-GENERATED by
// scripts/generate-commands.mjs. These tests capture the argv the generated
// `run` wrapper actually spawns, so a generator change cannot silently break the
// shipped TypeScript API — in particular the repeatable `--property` emission and
// the position of global flags relative to the `--` passthrough separator.

/**
 * Replace child_process.spawn with a fake that records the argv it is handed and
 * immediately resolves with a success exit code. winapp-cli-utils reads spawn off
 * the shared builtin module at call time, so mutating it here is observed by run().
 */
function captureSpawnArgs(): { calls: string[][] } {
  const state = { calls: [] as string[][] };
  mock.method(childProcess, 'spawn', ((_cmd: string, args: string[]) => {
    state.calls.push(args);
    const child = new EventEmitter() as EventEmitter & {
      stdout: EventEmitter;
      stderr: EventEmitter;
    };
    child.stdout = new EventEmitter();
    child.stderr = new EventEmitter();
    // Emit close after listeners are attached (spawn returns synchronously first).
    process.nextTick(() => child.emit('close', 0));
    return child;
  }) as unknown as typeof childProcess.spawn);
  return state;
}

afterEach(() => {
  mock.restoreAll();
});

test('run emits repeatable --property as separate flag/value pairs and keeps --quiet before the -- passthrough', async () => {
  const state = captureSpawnArgs();

  await run({ property: ['A=1', 'B=2'], appArgs: ['--flag'], quiet: true });

  assert.equal(state.calls.length, 1, 'winapp CLI should be spawned exactly once');
  const argv = state.calls[0];

  // Each --property value must be emitted as its own flag/value pair.
  const propValues: string[] = [];
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--property') propValues.push(argv[i + 1]);
  }
  assert.deepEqual(
    propValues,
    ['A=1', 'B=2'],
    'each property must be a separate --property flag/value pair'
  );

  // Global flags (e.g. --quiet) must come before the `--` passthrough separator so
  // winapp consumes them instead of forwarding them to the launched app.
  const sep = argv.indexOf('--');
  const quiet = argv.indexOf('--quiet');
  assert.ok(quiet !== -1, '--quiet should be present');
  assert.ok(sep !== -1, 'the -- passthrough separator should be present');
  assert.ok(quiet < sep, '--quiet must come before the -- passthrough separator');

  // App args are forwarded verbatim after the separator.
  assert.deepEqual(argv.slice(sep + 1), ['--flag'], 'app args are forwarded after --');
});

test('run accepts a single scalar --property value', async () => {
  const state = captureSpawnArgs();

  await run({ property: 'X=9' });

  const argv = state.calls[0];
  const propValues: string[] = [];
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--property') propValues.push(argv[i + 1]);
  }
  assert.deepEqual(propValues, ['X=9'], 'a scalar property is emitted as one --property pair');
  assert.equal(argv.indexOf('--'), -1, 'no passthrough separator without appArgs');
});
