using System.CommandLine;

namespace Winsdk.Cli.Commands;

internal class MsixInitCommand : Command
{
    public MsixInitCommand() : base("init", "Initialize MSIX package assets")
    {
        var sparseOption = new Option<bool>("--sparse")
        {
            Description = "Generate sparse package manifest"
        };
        var outputOption = new Option<string>("--output")
        {
            Description = "Output directory",
            DefaultValueFactory = (argumentResult) => Directory.GetCurrentDirectory()
        };
        var nameOption = new Option<string?>("--name")
        {
            Description = "Package name (default: folder name)",
        };
        var publisherOption = new Option<string?>("--publisher")
        {
            Description = "Publisher CN (default: CN=<current user>)",
        };
        var versionOption = new Option<string>("--version")
        {
            Description = "Version",
            DefaultValueFactory = (argumentResult) => "1.0.0.0"
        };
        var descriptionOption = new Option<string>("--description")
        {
            Description = "Description",
            DefaultValueFactory = (argumentResult) => "Windows app package bootstrap generated by winsdk. Update before distribution."
        };
        var executableOption = new Option<string?>("--executable")
        {
            Description = "Executable path/name (default: <name>.exe)"
        };

        Options.Add(sparseOption);
        Options.Add(outputOption);
        Options.Add(nameOption);
        Options.Add(publisherOption);
        Options.Add(versionOption);
        Options.Add(descriptionOption);
        Options.Add(executableOption);

        SetAction(async parseResult =>
        {
            var sparse = parseResult.GetValue(sparseOption);
            var outputDir = parseResult.GetRequiredValue(outputOption);
            var name = parseResult.GetValue(nameOption);
            var publisher = parseResult.GetValue(publisherOption);
            var description = parseResult.GetRequiredValue(descriptionOption);
            var version = parseResult.GetRequiredValue(versionOption);
            var executable = parseResult.GetValue(executableOption);

            var msix = new MsixService();
            await msix.GenerateMsixAssetsAsync(sparse, outputDir, name, publisher, description, version, executable);

            Console.WriteLine($"MSIX assets generated at: {outputDir}");
        });
    }
}