// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace WinApp.Cli.Services.Controls;

using System.Net.Http;

/// <summary>
/// Downloads a published sample index and maps it onto the internal
/// <see cref="Scenario"/> model. One HTTP request per source, whatever the size of the
/// corpus behind it — contrast a scraper, which reconstructs the same data from
/// repository layout and pays a request per control page and per snippet file.
///
/// <para>This is the whole client for a source that publishes an index under
/// <see href="https://github.com/microsoft/winappCli/issues/703">#703</see>. The document
/// shape is <c>docs/winui-sample-index.schema.json</c> and the mapping lives in
/// <see cref="SampleIndexParser"/>, so a new source needs a URL and a source id and
/// nothing else.</para>
/// </summary>
internal static class SampleIndexFetcher
{
    /// <summary>WinUI 3 Gallery, generated by its <c>tools/CatalogExporter</c> and validated
    /// against our published contract on every one of their PRs.</summary>
    public const string GalleryIndexUrl =
        "https://raw.githubusercontent.com/microsoft/WinUI-Gallery/main/catalog/windows-samples.json";

    /// <summary>microsoft-ui-reactor ReactorGallery. The first source to publish an index,
    /// and the file the shared contract was generalized from.</summary>
    public const string ReactorIndexUrl =
        "https://raw.githubusercontent.com/microsoft/microsoft-ui-reactor/main/samples/ReactorGallery/reactor-search-index.json";

    private static readonly HttpClient Http = new()
    {
        DefaultRequestHeaders = { { "User-Agent", "winapp-find-ui/1.0" } },
        Timeout = TimeSpan.FromSeconds(30)
    };

    /// <summary>
    /// Fetch <paramref name="indexUrl"/> and parse it, stamping <paramref name="sourceId"/>
    /// onto every scenario. The body is streamed through the shared byte-capped helper so an
    /// accidentally-huge upstream file can't exhaust memory.
    /// </summary>
    /// <returns>
    /// <c>tags</c> feeds <c>ProviderData.Tags</c> (search weight 3.0) and
    /// <c>curatedKeywords</c> feeds <c>ProviderData.Keywords</c> (weight 5.0).
    /// </returns>
    internal static async Task<(Scenario[] scenarios, Dictionary<string, string[]> tags, Dictionary<string, string[]> curatedKeywords)> FetchAsync(
        string indexUrl,
        string sourceId,
        CancellationToken cancellationToken = default)
    {
        var json = await ControlsHttpHelper.GetStringCappedAsync(Http, indexUrl, cancellationToken).ConfigureAwait(false);
        return SampleIndexParser.Parse(json, sourceId);
    }
}
