parameters:
  stable: 'false'
  DoEsrp: false
  signingIdentity:
    serviceName: ''
    appId: ''
    tenantId: ''
    akvName: ''
    authCertName: ''
    signCertName: ''

steps:
- task: PowerShell@2
  displayName: Build CLI
  inputs:
    pwsh: true
    filePath: $(System.DefaultWorkingDirectory)\scripts\build-cli.ps1
    arguments: '-Stable ${{ parameters.stable }} -SkipMsix'
- ${{ if eq(parameters['DoEsrp'], 'true') }}:
  - task: EsrpCodeSigning@5
    displayName: Code Sign ESRP - CLI
    inputs:
      ConnectedServiceName: ${{ parameters.signingIdentity.serviceName }}
      AppRegistrationClientId: ${{ parameters.signingIdentity.appId }}
      AppRegistrationTenantId: ${{ parameters.signingIdentity.tenantId }}
      AuthAKVName: ${{ parameters.signingIdentity.akvName }}
      AuthCertName: ${{ parameters.signingIdentity.authCertName }}
      AuthSignCertName: ${{ parameters.signingIdentity.signCertName }}
      FolderPath: '$(System.DefaultWorkingDirectory)/artifacts/cli/'
      Pattern: |
        win-arm64/winapp.exe
        win-x64/winapp.exe
      UseMinimatch: true
      signConfigType: inlineSignParams
      inlineOperation: |
        [
            {
                "KeyCode": "CP-230012",
                "OperationCode": "SigntoolSign",
                "Parameters": {
                    "OpusName": "Microsoft Windows Developer SDK CLI",
                    "OpusInfo": "https://github.com/Microsoft/WinAppCli",
                    "FileDigest": "/fd \"SHA256\"",
                    "PageHash": "/PH",
                    "TimeStamp": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                },
                "ToolName": "sign",
                "ToolVersion": "1.0"
            },
            {
                "KeyCode": "CP-230012",
                "OperationCode": "SigntoolVerify",
                "Parameters": {},
                "ToolName": "sign",
                "ToolVersion": "1.0"
            }
        ]
- task: PowerShell@2
  displayName: Bundle MSIX Packages
  inputs:
    pwsh: true
    filePath: $(System.DefaultWorkingDirectory)\scripts\package-msix.ps1
    arguments: '-Stable ${{ parameters.stable }}'
- ${{ if eq(parameters['DoEsrp'], 'true') }}:
  - task: EsrpCodeSigning@5
    displayName: Code Sign ESRP - MSIX Packages
    inputs:
      ConnectedServiceName: ${{ parameters.signingIdentity.serviceName }}
      AppRegistrationClientId: ${{ parameters.signingIdentity.appId }}
      AppRegistrationTenantId: ${{ parameters.signingIdentity.tenantId }}
      AuthAKVName: ${{ parameters.signingIdentity.akvName }}
      AuthCertName: ${{ parameters.signingIdentity.authCertName }}
      AuthSignCertName: ${{ parameters.signingIdentity.signCertName }}
      FolderPath: '$(System.DefaultWorkingDirectory)/artifacts/msix-packages/'
      Pattern: '*.msix'
      UseMinimatch: true
      signConfigType: inlineSignParams
      inlineOperation: |
        [
            {
                "KeyCode": "CP-230012",
                "OperationCode": "SigntoolSign",
                "Parameters": {
                    "OpusName": "Microsoft Windows Developer SDK CLI",
                    "OpusInfo": "https://github.com/Microsoft/WinAppCli",
                    "FileDigest": "/fd \"SHA256\"",
                    "PageHash": "/PH",
                    "TimeStamp": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                },
                "ToolName": "sign",
                "ToolVersion": "1.0"
            }
        ]
- task: CopyFiles@2
  displayName: Copy Artifacts - Test Results
  inputs:
    sourceFolder: '$(System.DefaultWorkingDirectory)/artifacts/'
    contents: '**/*.trx'
    targetFolder: '$(Build.ArtifactStagingDirectory)/TestResults'
- task: 1ES.PublishPipelineArtifact@1
  displayName: Upload Artifact - Test Results
  inputs:
    path: '$(Build.ArtifactStagingDirectory)/TestResults'
    artifactName: test-results
- task: CopyFiles@2
  displayName: Copy Artifacts - CLI Binaries
  inputs:
    sourceFolder: '$(System.DefaultWorkingDirectory)/artifacts/cli/'
    contents: '**'
    targetFolder: '$(Build.ArtifactStagingDirectory)/cli'
- task: 1ES.PublishPipelineArtifact@1
  displayName: Upload Artifact - CLI Binaries
  inputs:
    path: '$(Build.ArtifactStagingDirectory)/cli'
    artifactName: cli-binaries
- task: CopyFiles@2
  displayName: Copy Artifacts - NPM Package
  inputs:
    sourceFolder: '$(System.DefaultWorkingDirectory)/artifacts/'
    contents: '*.tgz'
    targetFolder: '$(Build.ArtifactStagingDirectory)/npmpackage'
- task: 1ES.PublishPipelineArtifact@1
  displayName: Upload Artifact - NPM Package
  inputs:
    path: '$(Build.ArtifactStagingDirectory)/npmpackage'
    artifactName: npm-package
- task: CopyFiles@2
  displayName: Copy Artifacts - MSIX packages
  inputs:
    sourceFolder: '$(System.DefaultWorkingDirectory)/artifacts/msix-packages/'
    contents: '*.msix'
    targetFolder: '$(Build.ArtifactStagingDirectory)/msix-packages'
- task: 1ES.PublishPipelineArtifact@1
  displayName: Upload Artifact - MSIX packages
  inputs:
    path: '$(Build.ArtifactStagingDirectory)/msix-packages'
    artifactName: msix-packages