// Copyright (c) Microsoft Corporation and Contributors. All rights reserved.
// Licensed under the MIT License.

using WinApp.Cli.Models;
using WinApp.Cli.Services;

namespace WinApp.Cli.Tests;

// Direct coverage for ConfigService.Parse / SanitizeScalar — the YAML reader
// behind every `config.Packages` consumer (NuGet install, MSIX runtime
// resolution, the JS bindings hash). Must agree with the TS sanitizeScalar
// in src/winapp-npm/src/jsbindings/yaml-packages-hash.ts.
[TestClass]
public class ConfigServiceTests
{
    [TestMethod]
    public void Parse_PlainPackages_ReturnsCleanNameVersion()
    {
        var yaml = "packages:\n  - name: Microsoft.WindowsAppSDK\n    version: 2.1.3\n";
        var cfg = ConfigService.Parse(yaml);
        Assert.AreEqual(1, cfg.Packages.Count);
        Assert.AreEqual("Microsoft.WindowsAppSDK", cfg.Packages[0].Name);
        Assert.AreEqual("2.1.3", cfg.Packages[0].Version);
    }

    [TestMethod]
    public void Parse_TrailingInlineComment_IsStripped()
    {
        // Regression: trailing `# …` used to be retained verbatim, producing
        // package names like "Microsoft.WindowsAppSDK   # bumped 2026-04"
        // that no downstream consumer (NuGet install, hash, log line) handled.
        var yaml = "packages:\n" +
                   "  - name: Microsoft.WindowsAppSDK   # bumped 2026-04\n" +
                   "    version: 2.1.3                  # latest stable\n";
        var cfg = ConfigService.Parse(yaml);
        Assert.AreEqual(1, cfg.Packages.Count);
        Assert.AreEqual("Microsoft.WindowsAppSDK", cfg.Packages[0].Name);
        Assert.AreEqual("2.1.3", cfg.Packages[0].Version);
    }

    [TestMethod]
    public void Parse_SingleQuotedScalars_StripsQuotesAndUnescapesEmbeddedQuotes()
    {
        // Quotes must come off, and `''` inside a single-quoted scalar is the
        // YAML-spec escape for a literal `'`.
        var yaml = "packages:\n" +
                   "  - name: 'Vendor.O''Reilly'\n" +
                   "    version: '1.0.0'\n";
        var cfg = ConfigService.Parse(yaml);
        Assert.AreEqual(1, cfg.Packages.Count);
        Assert.AreEqual("Vendor.O'Reilly", cfg.Packages[0].Name);
        Assert.AreEqual("1.0.0", cfg.Packages[0].Version);
    }

    [TestMethod]
    public void Parse_DoubleQuotedScalars_StripsOuterQuotes()
    {
        var yaml = "packages:\n" +
                   "  - name: \"Quoted.Pkg\"\n" +
                   "    version: \"4.5.6\"\n";
        var cfg = ConfigService.Parse(yaml);
        Assert.AreEqual(1, cfg.Packages.Count);
        Assert.AreEqual("Quoted.Pkg", cfg.Packages[0].Name);
        Assert.AreEqual("4.5.6", cfg.Packages[0].Version);
    }

    [TestMethod]
    public void Parse_HashInsideQuotedScalar_IsPreservedAsLiteral()
    {
        // `#` inside a quoted scalar is literal, not the start of an inline
        // comment. Don't accidentally truncate user data that legitimately
        // contains a `#`.
        var yaml = "packages:\n" +
                   "  - name: \"Has#Hash\"\n" +
                   "    version: '1.0#beta'\n";
        var cfg = ConfigService.Parse(yaml);
        Assert.AreEqual(1, cfg.Packages.Count);
        Assert.AreEqual("Has#Hash", cfg.Packages[0].Name);
        Assert.AreEqual("1.0#beta", cfg.Packages[0].Version);
    }

    [TestMethod]
    public void Parse_HashWithoutLeadingWhitespace_IsLiteral()
    {
        // Per YAML, an unquoted `#` only starts a comment when it follows
        // whitespace. `foo#bar` is a single scalar, not "foo" + comment.
        var yaml = "packages:\n" +
                   "  - name: Vendor.Pkg#suffix\n" +
                   "    version: 1.0.0\n";
        var cfg = ConfigService.Parse(yaml);
        Assert.AreEqual(1, cfg.Packages.Count);
        Assert.AreEqual("Vendor.Pkg#suffix", cfg.Packages[0].Name);
    }

    [TestMethod]
    public void Parse_FullLineComment_IsIgnored()
    {
        var yaml = "# pins generated by tooling\n" +
                   "packages:\n" +
                   "  # entries follow\n" +
                   "  - name: Foo\n" +
                   "    version: 1\n";
        var cfg = ConfigService.Parse(yaml);
        Assert.AreEqual(1, cfg.Packages.Count);
        Assert.AreEqual("Foo", cfg.Packages[0].Name);
    }

    [TestMethod]
    public void Parse_NameVersionOutsidePackagesBlock_IsIgnored()
    {
        // Regression for hash drift: only the `packages:` block contributes pins.
        // A `name:`/`version:` row that appears at indent 0 (or inside another
        // top-level section) must not bleed into the package list — otherwise
        // the C#-computed hash would diverge from the TS-computed one and
        // every `winapp restore` after a JS-bindings init would re-run.
        var yaml = "workspace:\n" +
                   "  name: ProjectFoo\n" +
                   "  version: 9.9.9\n" +
                   "packages:\n" +
                   "  - name: Microsoft.WindowsAppSDK\n" +
                   "    version: 2.1.3\n";
        var cfg = ConfigService.Parse(yaml);
        Assert.AreEqual(1, cfg.Packages.Count);
        Assert.AreEqual("Microsoft.WindowsAppSDK", cfg.Packages[0].Name);
        Assert.AreEqual("2.1.3", cfg.Packages[0].Version);
    }

    [TestMethod]
    public void Parse_PackagesAfterAnotherSection_StillParsed()
    {
        var yaml = "metadata:\n" +
                   "  name: outer\n" +
                   "packages:\n" +
                   "  - name: Foo\n" +
                   "    version: 1\n";
        var cfg = ConfigService.Parse(yaml);
        Assert.AreEqual(1, cfg.Packages.Count);
        Assert.AreEqual("Foo", cfg.Packages[0].Name);
    }

    [TestMethod]
    public void SanitizeScalar_EmptyInputs_ReturnEmptyString()
    {
        Assert.AreEqual(string.Empty, ConfigService.SanitizeScalar(""));
        Assert.AreEqual(string.Empty, ConfigService.SanitizeScalar("   "));
    }

    [TestMethod]
    public void SanitizeScalar_PreservesValueWhenOuterQuotesDoNotMatch()
    {
        // No matching outer quote pair — return the value as-is after comment cut.
        // E.g. `foo'bar` is a legitimate unquoted scalar with a literal apostrophe.
        // (Old `Trim('"','\'')` would have stripped trailing `bar` apostrophe; here we don't.)
        Assert.AreEqual("foo'bar", ConfigService.SanitizeScalar("foo'bar"));
    }

    [TestMethod]
    public void SanitizeScalar_DoubleQuotedWithBackslashEscape_KeepsEscapedQuoteInsideScalar()
    {
        // A `\"` inside a double-quoted scalar is an escape, not the closing quote,
        // so the closing `"` is the final char and the inner text is returned verbatim.
        Assert.AreEqual("a\\\"b", ConfigService.SanitizeScalar("\"a\\\"b\""));
    }

    [TestMethod]
    public void Parse_DashVersionThenBareName_CommitsPackage()
    {
        // Exercises the `- version:` and bare `name:` arms (list item that leads with
        // version). Order-independent commit must still produce one package.
        var yaml = "packages:\n" +
                   "  - version: 1.2.3\n" +
                   "    name: Foo.Bar\n";
        var cfg = ConfigService.Parse(yaml);
        Assert.AreEqual(1, cfg.Packages.Count);
        Assert.AreEqual("Foo.Bar", cfg.Packages[0].Name);
        Assert.AreEqual("1.2.3", cfg.Packages[0].Version);
    }

    [TestMethod]
    public void Parse_PackagesKeyWithInlineComment_StillStartsBlock()
    {
        // `packages:` may carry a trailing inline comment; the top-level-key probe must
        // still recognise it as the start of the packages block.
        var yaml = "packages:  # generated by tooling\n" +
                   "  - name: Foo\n" +
                   "    version: 1\n";
        var cfg = ConfigService.Parse(yaml);
        Assert.AreEqual(1, cfg.Packages.Count);
        Assert.AreEqual("Foo", cfg.Packages[0].Name);
    }

    [TestMethod]
    public void SanitizeScalar_QuotedPrefixWithTrailingText_NotTreatedAsFullyQuoted()
    {
        // `'abc'def` closes the quote mid-string, so the outer-quote strip must not apply
        // and the trailing text is retained verbatim.
        Assert.AreEqual("'abc'def", ConfigService.SanitizeScalar("'abc'def"));
    }

    [TestMethod]
    public void Load_WhenConfigFileMissing_ReturnsEmptyConfig()
    {
        using var temp = new TempDir();
        var service = new ConfigService(new CurrentDirectoryProvider(temp.Path))
        {
            ConfigPath = new FileInfo(Path.Combine(temp.Path, "winapp.yaml")),
        };

        Assert.IsFalse(service.Exists());
        var cfg = service.Load();
        Assert.AreEqual(0, cfg.Packages.Count);
    }

    [TestMethod]
    public void SaveThenLoad_RoundTripsPackages()
    {
        using var temp = new TempDir();
        var service = new ConfigService(new CurrentDirectoryProvider(temp.Path))
        {
            ConfigPath = new FileInfo(Path.Combine(temp.Path, "winapp.yaml")),
        };

        var cfg = new WinappConfig();
        cfg.Packages.Add(new PackagePin { Name = "Microsoft.WindowsAppSDK", Version = "1.6.0" });
        cfg.Packages.Add(new PackagePin { Name = "Vendor.Pkg", Version = "2.0.1" });

        service.Save(cfg);

        Assert.IsTrue(service.Exists(), "Save must produce a file on disk.");
        var written = File.ReadAllText(service.ConfigPath.FullName);
        StringAssert.Contains(written, "packages:");
        StringAssert.Contains(written, "- name: Microsoft.WindowsAppSDK");
        StringAssert.Contains(written, "version: 1.6.0");

        var reloaded = service.Load();
        Assert.AreEqual(2, reloaded.Packages.Count);
        Assert.AreEqual("Microsoft.WindowsAppSDK", reloaded.Packages[0].Name);
        Assert.AreEqual("1.6.0", reloaded.Packages[0].Version);
        Assert.AreEqual("Vendor.Pkg", reloaded.Packages[1].Name);
        Assert.AreEqual("2.0.1", reloaded.Packages[1].Version);
    }

    [TestMethod]
    public void Constructor_DefaultsConfigPathToWorkingDirectory()
    {
        using var temp = new TempDir();
        var service = new ConfigService(new CurrentDirectoryProvider(temp.Path));
        Assert.AreEqual(Path.Combine(temp.Path, "winapp.yaml"), service.ConfigPath.FullName);
    }

    /// <summary>Throwaway temp directory that cleans itself up.</summary>
    private sealed class TempDir : IDisposable
    {
        public string Path { get; }

        public TempDir()
        {
            Path = System.IO.Path.Combine(System.IO.Path.GetTempPath(), $"ConfigSvc_{Guid.NewGuid():N}");
            Directory.CreateDirectory(Path);
        }

        public void Dispose()
        {
            try
            {
                Directory.Delete(Path, true);
            }
            catch
            {
                // best-effort
            }
        }
    }
}
