<?xml version="1.0" encoding="utf-8"?>
<!--
  Microsoft.Windows.SDK.BuildTools.Extras.props (Multi-Targeting)
  
  This file is imported for multi-targeting projects.
  It imports the main props file.
-->
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="..\build\Microsoft.Windows.SDK.BuildTools.Extras.props" />
</Project>
