trigger:
  branches:
    include:
      - main
      - dev/**
pr: none

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
  parameters:
    sdl:
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared
        image: windows-latest
        os: windows
    stages:
    - stage: Build
      jobs:
      - job: Build
        pool:
          name: Azure-Pipelines-1ESPT-ExDShared
          image: windows-latest
          os: windows
          hostArchitecture: amd64
        steps:
          - checkout: self
          - task: UseDotNet@2
            displayName: Setup .NET 10
            inputs:
              version: 10.0.x
          - task: UseNode@1
            displayName: Setup Node.js 24
            inputs:
              version: '24.x'
          - script: move /Y $(Build.SourcesDirectory)\.pipelines\release-nuget.config $(Build.SourcesDirectory)\nuget.config
            displayName: Add release package source
          - task: NuGetAuthenticate@1
          - template: ./.pipelines/templates/build.yaml@self
            parameters:
              stable: 'false'
              DoEsrp: false
              signingIdentity: {}