trigger:
  branches:
    include:
      - rel/v*
pr: none

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

parameters:
  - name: DoEsrp
    type: boolean
    default: true
  - name: signingIdentity
    type: object
    default:
      serviceName: $(SigningServiceName)
      appId: $(SigningAppId)
      tenantId: $(SigningTenantId)
      akvName: $(SigningAKVName)
      authCertName: $(SigningAuthCertName)
      signCertName: $(SigningSignCertName)

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    sdl:
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared
        image: windows-latest
        os: windows
    stages:
    - stage: Build
      jobs:
      - job: Build
        pool:
          name: Azure-Pipelines-1ESPT-ExDShared
          image: windows-latest
          os: windows
          hostArchitecture: amd64
        steps:
          - checkout: self
          - task: UseDotNet@2
            displayName: Setup .NET 9
            inputs:
              version: 9.0.x
          - ${{ if eq(parameters.DoEsrp, 'true') }}:
            - task: UseDotNet@2
              displayName: Setup .NET 6.0 (For ESRP Task)
              inputs:
                packageType: runtime
                version: 6.0.x
          - task: UseNode@1
            displayName: Setup Node.js 24
            inputs:
              version: '24.x'
          - script: move /Y $(Build.SourcesDirectory)\.pipelines\release-nuget.config $(Build.SourcesDirectory)\nuget.config
            displayName: Add release package source
          - task: NuGetAuthenticate@1
          - task: PowerShell@2
            displayName: Replace Stubbed Files
            inputs:
              filePath: '.pipelines/Unstub.ps1'
          - template: ./.pipelines/templates/build.yaml@self
            parameters:
              stable: 'true'
              DoEsrp: ${{ parameters.DoEsrp }}
              signingIdentity: ${{ parameters.signingIdentity }}
          - task: PowerShell@2
            name: SetMeta
            displayName: Export version
            inputs:
              targetType: inline
              script: |
                # Get version info
                $versionJson = Get-Content "version.json" | ConvertFrom-Json
                $baseVersion = $versionJson.version
                $fullVersion = "$baseVersion"

                Write-Host "Version: $fullVersion"

                Write-Host "##vso[task.setvariable variable=version;isOutput=true]$fullVersion"

    - stage: Release
      displayName: Create GitHub Pre-release
      dependsOn: Build
      variables:
        version: $[ stageDependencies.Build.Build.outputs['SetMeta.version'] ]
      jobs:
      - job: create_release
        pool:
          name: Azure-Pipelines-1ESPT-ExDShared
          image: windows-latest
          os: windows
          hostArchitecture: amd64
        displayName: GitHub Pre-release
        templateContext:
          type: releaseJob
          isProduction: true
          inputs:
          - input: pipelineArtifact
            artifactName: cli-binaries
            targetPath: $(Pipeline.Workspace)/cli-binaries
          - input: pipelineArtifact
            artifactName: npm-package
            targetPath: $(Pipeline.Workspace)/npm-package
          - input: pipelineArtifact
            artifactName: msix-packages
            targetPath: $(Pipeline.Workspace)/msix-packages
        steps:
          - task: ArchiveFiles@2
            displayName: Archive CLI binaries - x64
            inputs:
              rootFolderOrFile: $(Pipeline.Workspace)/cli-binaries/win-x64
              includeRootFolder: false
              archiveFile: $(Pipeline.Workspace)/winappcli-x64.zip

          - task: ArchiveFiles@2
            displayName: Archive CLI binaries - arm64
            inputs:
              rootFolderOrFile: $(Pipeline.Workspace)/cli-binaries/win-arm64
              includeRootFolder: false
              archiveFile: $(Pipeline.Workspace)/winappcli-arm64.zip

          - task: GitHubRelease@1
            displayName: "Create GitHub Pre-release"
            inputs:
              gitHubConnection: 'github-service-connection'
              repositoryName: 'microsoft/winappcli'
              action: 'create'
              target: '$(Build.SourceVersion)'
              tagSource: 'userSpecifiedTag'
              tag: 'v$(version)'
              title: 'Pre-release v$(version)'
              isPreRelease: true
              assets: |
                $(Pipeline.Workspace)/winappcli-x64.zip
                $(Pipeline.Workspace)/winappcli-arm64.zip
                $(Pipeline.Workspace)/msix-packages/*.msix
                $(Pipeline.Workspace)/npm-package/*.tgz
              assetUploadMode: 'delete'
              addChangeLog: false
              releaseNotesSource: 'inline'
              releaseNotesInline: |
                🚀 **Automated Pre-release Build**

                Version: `$(version)`
                Commit: `$(Build.SourceVersion)`

                ## Installation Options

                ### 📦 Standalone CLI Binaries
                1. Download `winappcli-x64.zip` for x64 or `winappcli-arm64.zip` for ARM64
                2. Extract to your desired location
                3. Add to PATH or run directly: `winapp.exe`

                ### 📚 NPM Package (for Electron or NodeJS)
                ```bash
                npm install microsoft-winappcli-$(version).tgz
                ```

                ## What's Included
                - ✅ Standalone CLI binaries (x64 and ARM64)
                - ✅ NPM package for NodeJS/Electron integration