trigger:
  branches:
    include:
      - rel/v*
pr: none

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

parameters:
  - name: DoEsrp
    type: boolean
    default: true
  - name: signingIdentity
    type: object
    default:
      serviceName: $(SigningServiceName)
      appId: $(SigningAppId)
      tenantId: $(SigningTenantId)
      akvName: $(SigningAKVName)
      authCertName: $(SigningAuthCertName)
      signCertName: $(SigningSignCertName)
      signTTSCertName: $(SigningSignTTSCertName)

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    sdl:
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared
        image: windows-latest
        os: windows
    stages:
    - stage: Build
      jobs:
      - job: Build
        pool:
          name: Azure-Pipelines-1ESPT-ExDShared
          image: windows-latest
          os: windows
          hostArchitecture: amd64
        steps:
          - checkout: self
          - task: UseDotNet@2
            displayName: Setup .NET 10
            inputs:
              version: 10.0.x
          - ${{ if eq(parameters.DoEsrp, 'true') }}:
            - task: UseDotNet@2
              displayName: Setup .NET 6.0 (For ESRP Task)
              inputs:
                packageType: runtime
                version: 6.0.x
          - task: UseNode@1
            displayName: Setup Node.js 24
            inputs:
              version: '24.x'
          - script: move /Y $(Build.SourcesDirectory)\.pipelines\release-nuget.config $(Build.SourcesDirectory)\nuget.config
            displayName: Add release package source
          - task: NuGetAuthenticate@1
          - task: PowerShell@2
            displayName: Replace Stubbed Files
            inputs:
              filePath: '.pipelines/Unstub.ps1'
              arguments: '-TelemetryProviderGuid "$(TelemetryProviderGuid)"' 
          - template: ./.pipelines/templates/build.yaml@self
            parameters:
              stable: 'true'
              DoEsrp: ${{ parameters.DoEsrp }}
              signingIdentity: ${{ parameters.signingIdentity }}
          - task: PowerShell@2
            name: SetMeta
            displayName: Export version
            inputs:
              targetType: inline
              script: |
                # Get version info
                $versionJson = Get-Content "version.json" | ConvertFrom-Json
                $baseVersion = $versionJson.version
                $fullVersion = "$baseVersion"

                Write-Host "Version: $fullVersion"

                Write-Host "##vso[task.setvariable variable=version;isOutput=true]$fullVersion"

    - stage: Release_GitHub
      displayName: Create GitHub Release
      dependsOn: Build
      variables:
        version: $[ stageDependencies.Build.Build.outputs['SetMeta.version'] ]
      jobs:
      - job: create_github_release
        pool:
          name: Azure-Pipelines-1ESPT-ExDShared
          image: windows-latest
          os: windows
          hostArchitecture: amd64
        displayName: GitHub Release
        templateContext:
          type: releaseJob
          isProduction: true
          inputs:
          - input: pipelineArtifact
            artifactName: cli-binaries
            targetPath: $(Pipeline.Workspace)/cli-binaries
          - input: pipelineArtifact
            artifactName: npm-package
            targetPath: $(Pipeline.Workspace)/npm-package
          - input: pipelineArtifact
            artifactName: msix-packages
            targetPath: $(Pipeline.Workspace)/msix-packages
        steps:
          - task: ArchiveFiles@2
            displayName: Archive CLI binaries - x64
            inputs:
              rootFolderOrFile: $(Pipeline.Workspace)/cli-binaries/win-x64
              includeRootFolder: false
              archiveFile: $(Pipeline.Workspace)/winappcli-$(version)-x64.zip

          - task: ArchiveFiles@2
            displayName: Archive CLI binaries - arm64
            inputs:
              rootFolderOrFile: $(Pipeline.Workspace)/cli-binaries/win-arm64
              includeRootFolder: false
              archiveFile: $(Pipeline.Workspace)/winappcli-$(version)-arm64.zip

          - task: GitHubRelease@1
            displayName: "Create GitHub Release"
            inputs:
              gitHubConnection: 'github-service-connection'
              repositoryName: 'microsoft/winappcli'
              action: 'create'
              target: '$(Build.SourceVersion)'
              tagSource: 'userSpecifiedTag'
              tag: 'v$(version)'
              title: 'Release v$(version)'
              isPreRelease: true
              assets: |
                $(Pipeline.Workspace)/winappcli-*.zip
                $(Pipeline.Workspace)/msix-packages/*.msix
                $(Pipeline.Workspace)/npm-package/*.tgz
              assetUploadMode: 'delete'
              addChangeLog: false
              releaseNotesSource: 'inline'
              releaseNotesInline: |
                🚀 **Automated Release Build**

                Version: `$(version)`
                Commit: `$(Build.SourceVersion)`

                ## Installation Options

                ### 📦 MSIX Installer (Recommended)
                1. Download `winappcli_$(version).0_x64.msix` for x64 or `winappcli_$(version).0_arm64.msix` for ARM64
                2. Double-click to install
                3. Automatically added to PATH

                ### 📦 Standalone CLI Binaries
                1. Download `winappcli-$(version)-x64.zip` for x64 or `winappcli-$(version)-arm64.zip` for ARM64
                2. Extract to your desired location
                3. Add to PATH or run directly: `winapp.exe`

                ### 📚 NPM Package (for Electron or NodeJS)
                ```bash
                npm install microsoft-winappcli-$(version).tgz
                ```

                ## What's Included
                - ✅ MSIX installer packages (x64 and ARM64)
                - ✅ Standalone CLI binaries (x64 and ARM64)
                - ✅ NPM package for NodeJS/Electron integration

    # Commented out ESRP release to npm for now
    # - ${{ if eq(parameters.DoEsrp, 'true') }}:
    #   - stage: Release_Npm
    #     displayName: Create Npm Release
    #     dependsOn: Release_GitHub
    #     jobs:
    #     - job: create_npm_release
    #       pool:
    #         name: Azure-Pipelines-1ESPT-ExDShared
    #         image: windows-latest
    #         os: windows
    #         hostArchitecture: amd64
    #       displayName: NPM Release
    #       templateContext:
    #         type: releaseJob
    #         isProduction: true
    #         inputs:
    #         - input: pipelineArtifact
    #           artifactName: npm-package
    #           targetPath: $(Pipeline.Workspace)/npm-package
    #       steps:
    #         - task: EsrpRelease@10
    #           condition: always()
    #           inputs:
    #             ConnectedServiceName: ${{ parameters.signingIdentity.serviceName }}
    #             usemanagedidentity: true
    #             keyvaultname: ${{ parameters.signingIdentity.akvName }}
    #             signcertname: ${{ parameters.signingIdentity.signTTSCertName }}
    #             clientid: ${{ parameters.signingIdentity.appId }}
    #             intent: 'PackageDistribution'
    #             contenttype: 'npm'
    #             contentsource: 'Folder'
    #             folderlocation: $(Pipeline.Workspace)/npm-package/
    #             waitforreleasecompletion: true
    #             owners: '$(EsrpOwnersEmail)'
    #             approvers: '$(EsrpApproversEmail)'
    #             serviceendpointurl: 'https://api.esrp.microsoft.com'
    #             mainpublisher: 'winappcli'
    #             domaintenantid: ${{ parameters.signingIdentity.tenantId }}

    - stage: Release_WinGet
      displayName: Create WinGet Release
      dependsOn: [Build, Release_GitHub]
      variables:
        version: $[ stageDependencies.Build.Build.outputs['SetMeta.version'] ]
      jobs:
      - job: create_winget_release
        pool:
          name: Azure-Pipelines-1ESPT-ExDShared
          image: windows-latest
          os: windows
          hostArchitecture: amd64
        displayName: WinGet Release
        templateContext:
          type: releaseJob
          isProduction: true
        steps:
          - task: PowerShell@2
            displayName: "Publish to WinGet"
            env:
              # PAT lasts 90 days, regenerate as needed and re-run if it failes due to authentication
              WINGET_CREATE_GITHUB_TOKEN: $(GITHUB_TOKEN)
              GH_TOKEN: $(GITHUB_TOKEN)
            inputs:
              targetType: 'inline'
              script: |
                # Download and install C++ Runtime framework package
                Write-Host "Installing VCLibs dependency..."
                $vcLibsFile = "Microsoft.VCLibs.x64.14.00.Desktop.appx"
                Invoke-WebRequest https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx -OutFile $vcLibsFile
                Add-AppxPackage $vcLibsFile
                
                # Install gh
                Write-Host "Installing gh..."
                winget install --id GitHub.cli --source winget --silent --accept-source-agreements
                if ($LASTEXITCODE -ne 0) {
                  Write-Host "winget returned exit code: $LASTEXITCODE"
                  Write-Host "Continuing in case gh is already installed..."
                }

                # Download and install wingetcreate
                Write-Host "Installing wingetcreate..."
                $wingetCreateBundle = "wingetcreate.msixbundle"
                Invoke-WebRequest https://aka.ms/wingetcreate/latest/msixbundle -OutFile $wingetCreateBundle
                Add-AppxPackage $wingetCreateBundle

                # WinGetCreate uses an existing fork of the microsoft/winget-pkgs repo to create the PR
                # that updates the main repo.  This fork will be under the account attached to the token.
                # We need to keep this fork up-to-date, otherwise the wingetcreate command will fail.
                # See: https://github.com/microsoft/winget-create/issues/502
                Write-Host "Syncing winget-pkgs fork..."
                & "$env:ProgramFiles\GitHub CLI\gh.exe" repo sync $(WingetPkgsFork) -b master
                if ($LASTEXITCODE -ne 0) {
                  Write-Error "Failed to sync winget-pkgs fork. Exit code: $LASTEXITCODE"
                  exit $LASTEXITCODE
                }
                Write-Host "Fork synced successfully."
                
                # Get the installer URLs from the GitHub release
                $x64MsixUrl = "https://github.com/microsoft/winappcli/releases/download/v$(version)/winappcli_$(version).0_x64.msix"
                $arm64MsixUrl = "https://github.com/microsoft/winappcli/releases/download/v$(version)/winappcli_$(version).0_arm64.msix"
                
                Write-Host "Submitting to WinGet..."
                Write-Host "Version: $(version)"
                Write-Host "x64 MSIX: $x64MsixUrl"
                Write-Host "ARM64 MSIX: $arm64MsixUrl"
                
                # Submit to WinGet repository
                wingetcreate update Microsoft.WinAppCli `
                  --version $(version) `
                  --urls $x64MsixUrl $arm64MsixUrl `
                  --submit
