// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

using System.Linq;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Navigation;

namespace winui_app;

public sealed class BenchRow(int index)
{
    public string Title { get; } = $"Item {index}";
    public string Detail { get; } = $"Secondary text for row {index}";
    public string Index { get; } = index.ToString();
}

public sealed partial class HomePage : Page
{
    public HomePage() => InitializeComponent();
}

public sealed partial class EmptyPage : Page
{
    public EmptyPage() => InitializeComponent();
}

public sealed partial class ListPage : Page
{
    public ListPage()
    {
        InitializeComponent();
        List.ItemsSource = Enumerable.Range(0, 10_000).Select(i => new BenchRow(i)).ToList();
    }
}

// HeavyPage.xaml is generated by scripts/devtools-perf.ps1: a XAML-authored page with many cards.
public sealed partial class HeavyPage : Page
{
    public HeavyPage() => InitializeComponent();
}

public sealed partial class BigTreePage : Page
{
    public BigTreePage() => InitializeComponent();

    protected override void OnNavigatedTo(NavigationEventArgs e)
    {
        var count = e.Parameter is int n ? n : 1000;
        Items.ItemsSource = Enumerable.Range(0, count).Select(i => new BenchRow(i)).ToList();
    }
}
